name: Refresh API Data
on: workflow_dispatch
permissions:
  contents: write
jobs:
  refresh-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'v14.18.1'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Fetch API Data
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://api.lorcast.com/v0
          configuration: '{ "method": "GET" }'
          save-location: assets
          save-name: allCards
          set-output: false
          
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main # Pushes the updates to the main branch.
          folder: assets # The location of the data.json file saved by the Fetch API Data action.
          target-folder: static/data # Saves the data into the 'data' directory on the main branch.
